### ISSUE TITLE
/userStatus endpoint

### ISSUE THREAD

**Issue by hcape** [Antidose/Server#29]
Need to get the users status (active/inactive) to show it to them on the settings page.
Need to change the users status when they click the toggle button.

btw the default when a user registers should be active 

- Get status: send a user token, receive the status (string or bool whatever it is), error if the user can't be found I guess (which probably shouldnt happen)

-Set status: send a user token and a status, response should be a success if it slid in the DB, fail message otherwise

**Comment by geofflorne** [comment]
https://github.com/Antidose/Server/pull/32
